export const scenes = [
  {
    name: 'Resonance',
    tag: 'Órbitas de luz',
    kicker: 'SONIDO HECHO MATERIA',
    description: 'Cada frecuencia deja su órbita.',
    category: 'ARTE GENERATIVO',
    info: 'Un núcleo de filamentos que respira con los graves. El espectro de frecuencias deforma cada órbita, los medios retuercen su superficie y los transitorios envían ondas de luz a través de la materia.',
  },
  {
    name: 'Chromaflow',
    tag: 'Materia líquida',
    kicker: 'EL COLOR TIENE FRECUENCIA',
    description: 'Deja que la música se derrame.',
    category: 'CAMPO FLUIDO',
    info: 'Capas de luz se entrelazan en un campo fluido. Los graves ensanchan las corrientes, los medios alteran sus pliegues y los agudos iluminan los bordes. La amplitud acelera el flujo y los golpes desplazan la mezcla de color.',
  },
  {
    name: 'Hyperdrive',
    tag: 'Horizonte espectral',
    kicker: 'MÁS ALLÁ DEL HORIZONTE',
    description: 'Un paisaje construido con sonido.',
    category: 'PAISAJE DIGITAL',
    info: 'Los ataques graves aceleran la carretera, abren la perspectiva y lanzan un barrido luminoso desde el horizonte. Los ataques medios encienden la retícula y los agudos disparan el brillo del espectro. Entre golpes, el impulso cae.',
  },
  {
    name: 'Kaleidoscope',
    tag: 'Simetría infinita',
    kicker: 'EL ORDEN DEL CAOS',
    description: 'La música encuentra su geometría.',
    category: 'GEOMETRÍA VIVA',
    info: 'Un mosaico caleidoscópico de cristales. Los medios abren los pétalos, el espectro dibuja sus bordes y los graves expanden la simetría. Cada transitorio inyecta un pulso breve en los reflejos.',
  },
  {
    name: 'Stardust',
    tag: 'Viaje interestelar',
    kicker: 'SOMOS POLVO DE ESTRELLAS',
    description: 'Piérdete entre miles de frecuencias.',
    category: 'ESPACIO PROFUNDO',
    info: 'Un túnel estelar que acelera con los golpes. Los graves expanden el campo y alargan las estelas; los ataques agudos encienden ráfagas de partículas. Las ondas del núcleo se reservan para golpes marcados, con al menos 1,4 segundos entre ellas y un brillo suave. Los demás acentos siguen moviendo las estrellas.',
  },
  {
    name: 'Beat Runner',
    tag: 'Plataformas musical',
    kicker: 'LA CANCIÓN ES EL MANDO',
    description: 'Sigue el pulso. Recoge la melodía.',
    category: 'EXPERIMENTO 2D',
    info: 'Un viaje para correr, saltar y recoger notas. Los golpes marcados disparan saltos completos, separados por un tramo de carrera: nunca se encadenan impulsos en el aire. Los graves regulan la altura y la intensidad, la velocidad. Los medios atraen notas cercanas y los agudos las iluminan. Las notas bajas se recogen corriendo; los arcos ámbar recompensan los saltos. Los acentos que no provocan saltos siguen iluminando el escenario. Las bandas son aproximaciones espectrales, no identificación de instrumentos.',
  },
];
